# Generated by Django 3.0.3 on 2020-02-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='adventure.ItemInstance'),
        ),
        migrations.AlterField(
            model_name='room',
            name='enemy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.EnemyInstance'),
        ),
        migrations.AlterField(
            model_name='room',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.Inventory'),
        ),
    ]
