# Generated by Django 3.0.3 on 2020-02-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='hp',
        ),
        migrations.CreateModel(
            name='EnemyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.PositiveIntegerField(default=10)),
                ('defense', models.PositiveIntegerField(default=10)),
                ('hp', models.PositiveIntegerField(default=10)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Enemy')),
            ],
        ),
    ]
