# Generated by Django 3.0.3 on 2020-02-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200205_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='enemy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.EnemyInstance'),
        ),
    ]
