# Generated by Django 3.0.3 on 2020-02-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200205_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.Inventory'),
        ),
    ]
