# Generated by Django 3.0.3 on 2020-02-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_room_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.Inventory'),
        ),
    ]
