# Generated by Django 3.0.3 on 2020-02-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_player_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.Room'),
        ),
    ]
