# Generated by Django 3.0.3 on 2020-02-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_auto_20200205_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='mp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='enemy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adventure.Enemy'),
        ),
    ]
