# Generated by Django 3.0.3 on 2020-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_auto_20200205_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='attack',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='defense',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
